export default {
  user: {
    userId: "User Id",
    nic: "NIC",
    email: "Email",
    mobileNo: "Mobile No",
  },
  driver: {
    licenceNo: "Licence No",
    issueDate: "Licence Issue Date",
    expireDate: "Licence Expiry Date",
    administrativeNo: "Administrative No",
    holdersSignature: "Holder's Signature",
    vehicleCategories: "Vehicle Categories",
  },
  vehicle: {
    registerNo: "Register No",
    chassisNo: "Chassis No",
    currentOwnerName: "Current Owner Name",
    currentOwnerAddress: "Current Owner Address",
    engineNo: "Engine No",
    vehicleClass: "Vehicle Class",
    stateWhenRegister: "State When Register",
    color: "Vehicle Color",
    engineCapacity: "Engine Capacity",
    fuelType: "Fuel Type",
    yearOfManufacture: "Year Of Manufacture",
    previousOwners: "Previous Owners",
  },
  people: {
    name: "Name",
    nic: "NIC",
    issueDate: "NIC Issue Date",
    dob: "Date of Birth",
    birthPlace: "Birth Place",
    address: "Address",
    gender: "Gender",
    job: "Student",
  },
};
